# Generated by Django 2.1.5 on 2020-08-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bornapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('choices', models.CharField(choices=[('GAY', 'Gay'), ('NOTGAY', 'Not gay'), ('FURRY', 'Furry'), ('ANIME', 'Anime'), ('WEIRDSHIT', 'Weird Shit')], default='GAY', max_length=10)),
            ],
        ),
    ]
