# Generated by Django 2.1.5 on 2021-01-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bornapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bornapp',
        ),
    ]
